/**
 * Cross-seam E2E: replays NDJSON produced by the REAL Scala engine
 * (SessionEventStream + JsonEvents, pinned as golden fixtures by
 * AgentEventFixturesSpec) through the REAL reducer + timeline adapter.
 *
 * The historical subagent bugs (duplicated 风控员 rows, one finish event
 * closing every row of the same agent) lived exactly in this seam — both
 * sides' own tests were green. After EVERY event this test asserts the
 * rendering invariants that <Static> depends on:
 *
 *   1. every timeline item id is unique (duplicate ids corrupt scrollback);
 *   2. the settled sequence is append-only and byte-frozen — a settled item
 *      never changes, moves, or disappears;
 *   3. agentRuns are keyed uniquely by runId.
 *
 * Fixtures are regenerated by the Scala spec (FAST_REGEN_FIXTURES=1); if the
 * engine's event shape drifts, the Scala side fails first, and this test
 * verifies the UI still upholds its contract against the new shape.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {bridgeEventSchema, type BridgeEvent} from '../rpc/protocol.js';
import {initialState, type AgentRun, type UiState} from '../state/model.js';
import {reducer} from '../state/reducer.js';
import {turnsToTimeline} from '../state/timeline/turnAdapter.js';
import type {TimelineItem} from '../state/timeline/model.js';

const fixturesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures');

function fixtureEvents(name: string): BridgeEvent[] {
	const lines = readFileSync(path.join(fixturesDir, name), 'utf8')
		.split(/\r?\n/).map(l => l.trim()).filter(Boolean);
	return lines.map(line => {
		const {payload} = JSON.parse(line) as {payload: unknown};
		const parsed = bridgeEventSchema.safeParse(payload);
		// Protocol contract: every line the engine emits must parse on the TS side.
		assert.ok(parsed.success, `engine event violates protocol schema: ${line}\n${parsed.success ? '' : parsed.error}`);
		return parsed.data;
	});
}

type Replay = {
	finalState: UiState;
	/** agentRuns snapshot after every event. */
	runSnapshots: AgentRun[][];
};

function settled(items: TimelineItem[]): TimelineItem[] {
	return items.filter(item => item.pending !== true);
}

function assertInvariants(items: TimelineItem[], prevSettled: string[], step: string): string[] {
	const ids = items.map(item => item.id);
	assert.equal(new Set(ids).size, ids.length,
		`duplicate timeline item ids at ${step}: ${ids.filter((id, i) => ids.indexOf(id) !== i).join(', ')}`);

	// The <Static> contract: previously settled items are already printed to
	// scrollback — they must reappear identically, in order, at the front.
	const settledNow = settled(items).map(item => JSON.stringify(item));
	assert.deepEqual(settledNow.slice(0, prevSettled.length), prevSettled,
		`settled prefix mutated at ${step} — printed scrollback would be corrupted`);
	return settledNow;
}

function replay(fixture: string): Replay {
	const events = fixtureEvents(fixture);
	let state = reducer(initialState, {type: 'engine_event', event: {type: 'ready'} as BridgeEvent});
	state = reducer(state, {type: 'submit_user', text: '组建科创板投研小组', clientMessageId: 'client-e2e'});

	let prevSettled = settled(turnsToTimeline(state).items).map(item => JSON.stringify(item));
	const runSnapshots: AgentRun[][] = [];

	for (const [index, event] of events.entries()) {
		state = reducer(state, {type: 'engine_event', event});
		prevSettled = assertInvariants(turnsToTimeline(state).items, prevSettled, `${fixture}#${index} (${event.type})`);

		const runIds = state.agentRuns.map(ar => ar.runId);
		assert.equal(new Set(runIds).size, runIds.length,
			`duplicate agentRun runIds at ${fixture}#${index}: ${runIds.join(', ')}`);
		runSnapshots.push(state.agentRuns.map(ar => ({...ar})));
	}
	return {finalState: state, runSnapshots};
}

/** Last snapshot before run_done wipes agentRuns — what the user actually saw. */
function lastPopulated(snapshots: AgentRun[][]): AgentRun[] {
	return [...snapshots].reverse().find(runs => runs.length > 0) ?? [];
}

test('repeat: three delegations to the same agent stay three distinct rows', () => {
	const {runSnapshots} = replay('engine-agent-repeat.jsonl');
	const rows = lastPopulated(runSnapshots);

	assert.equal(rows.length, 3, 'one row per delegation, no ghosts, no merging');
	assert.deepEqual(rows.map(row => row.runId), ['run-r1', 'run-r2', 'run-r3']);
	assert.deepEqual(rows.map(row => row.status), ['failed', 'failed', 'success']);
	// The regression: one finish event must not overwrite the other rows' stats.
	assert.deepEqual(rows.map(row => row.toolCalls), [1, 2, 1]);
	assert.ok(rows.every(row => row.name === '风控员'));
});

test('interleaved: tool events attribute to the right run, never bleed', () => {
	const {runSnapshots} = replay('engine-agent-interleaved.jsonl');
	const rows = lastPopulated(runSnapshots);

	assert.equal(rows.length, 2);
	const data = rows.find(row => row.runId === 'run-d1');
	const risk = rows.find(row => row.runId === 'run-r1');
	assert.equal(data?.toolCalls, 1);
	assert.equal(risk?.toolCalls, 2);
	assert.equal(data?.status, 'success');
	assert.equal(risk?.status, 'success');
});

test('dup-runcreated: a replayed start event never duplicates the row', () => {
	const {runSnapshots} = replay('engine-agent-dup-runcreated.jsonl');
	const maxRows = Math.max(...runSnapshots.map(runs => runs.length));
	assert.equal(maxRows, 1);
	assert.equal(lastPopulated(runSnapshots)[0]?.status, 'success');
});

test('cancel: bridge truncates the post-cancel tail; UI ends clean and idle', () => {
	// The Scala side proves the truncation (no leaked events after the parent's
	// RunCancelled make it into the pinned fixture); this side proves the UI
	// digests a cancelled delegation cleanly.
	const {finalState} = replay('engine-agent-cancel.jsonl');

	assert.ok(!JSON.stringify(finalState.transcript.entries).includes('GHOST'),
		'post-cancel engine leaks must never reach the UI state');
	const lastAssistant = [...finalState.transcript.entries].reverse().find(e => e.role === 'assistant');
	assert.equal(lastAssistant?.status, 'cancelled');
	assert.equal(finalState.agentRuns.length, 0, 'no agent row may keep spinning after the cancel');
	assert.equal(finalState.running, false);
	assert.equal(finalState.inputMode, 'normal');
});

test('single: happy path ends with a completed run and a clean final state', () => {
	const {finalState, runSnapshots} = replay('engine-agent-single.jsonl');
	assert.equal(lastPopulated(runSnapshots)[0]?.status, 'success');
	// run_done clears live agent rows; the turn itself closed successfully.
	assert.equal(finalState.agentRuns.length, 0);
	const lastAssistant = [...finalState.transcript.entries].reverse().find(e => e.role === 'assistant');
	assert.equal(lastAssistant?.status, 'done');
});

test('grep NoSuchFile: Bridge NDJSON unlocks composer; failed tool is not left running', () => {
	// Pinned by AgentEventFixturesSpec (engine-grep-nosuchfile.jsonl) from the
	// real SessionEventStream + JsonEvents projection of ToolFinished(failed).
	const {finalState} = replay('engine-grep-nosuchfile.jsonl');

	assert.equal(finalState.running, false);
	assert.equal(finalState.inputMode, 'normal');

	const items = turnsToTimeline(finalState).items;
	const groups = items.filter(item => item.kind === 'tool_group');
	assert.equal(groups.length, 1, 'grep tool card must appear in the timeline');
	assert.ok(groups.every(item => item.pending !== true), 'tool group must settle');
	const grep = groups[0]?.kind === 'tool_group' ? groups[0].tools.find(t => t.tool === 'grep') : undefined;
	assert.ok(grep, 'grep tool run present');
	assert.equal(grep?.status, 'failed');
	assert.match(JSON.stringify(grep?.output ?? ''), /NoSuchFileException/);

	const lastAssistant = [...finalState.transcript.entries].reverse().find(e => e.role === 'assistant');
	assert.equal(lastAssistant?.status, 'done');
});
