/**
 * Full-chain ghost regression for subagent rows: replays engine-authored agent
 * events (engine-agent-repeat.jsonl, generated by AgentEventFixturesSpec from
 * the REAL SessionEventStream) through the real Ink UI in a true PTY, then
 * parses the final terminal buffer.
 *
 * The historical bug: three delegations to the same 风控员 agent shared one
 * agentId, producing duplicate timeline ids → <Static> repaint storms → dozens
 * of leftover "风控员 N tools" snapshot rows in scrollback. A healthy replay
 * leaves at most the three real rows (usually zero: run_done clears them).
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createReplayEngineHarness, gracefulExit} from './helpers/e2eHarness.js';

test('PTY agent rows: repeated delegations leave no ghost snapshot rows', {timeout: 120_000}, async t => {
	const h = await createReplayEngineHarness(t, 'engine-agent-repeat.jsonl', {
		// Let intermediate frames actually render so ghost frames CAN happen.
		FAST_REPLAY_EVENT_DELAY_MS: '60',
	});
	if (!h) return;

	try {
		await h.waitFor(() => h.transcript.includes('输入消息，或 /help 查看命令'), 'ready prompt', 30_000);
		await h.submit('组建科创板投研小组');

		await h.waitFor(() => h.transcript.includes('风控结论'), 'final answer', 60_000);
		// The subagent rows must have been visible at some point during the run.
		assert.match(h.transcript, /风控员/);
		await h.waitForIdle(30_000);
		await new Promise(resolve => setTimeout(resolve, 500));

		const screen = await h.screenText();
		const lines = screen.split('\n');

		// THE assertion: every "风控员 … tools" line still in the buffer after the
		// run is a leftover snapshot. Three real rows existed; the bug left 20+.
		const agentRows = lines.filter(line => /风控员/.test(line) && /tools/.test(line));
		assert.ok(agentRows.length <= 3,
			`found ${agentRows.length} residual agent rows (ghost snapshots):\n${agentRows.slice(0, 10).join('\n')}`);

		// The final answer renders exactly once (no duplicated static history).
		const finalCount = screen.match(/风控结论/g)?.length ?? 0;
		assert.equal(finalCount, 1, `final answer should render exactly once, saw ${finalCount}`);
	} finally {
		if (!h.exited) {
			try { await gracefulExit(h); } catch { h.cleanup(); }
		}
	}
});
