import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CATEGORY } from '../../../packages/web/ui/src/themes/categories.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const paletteDir = resolve(root, 'packages/web/ui/src/themes/palette');
const tokensPath = resolve(root, 'apps/mobile/src/theme/tokens.ts');
const palettesPath = resolve(root, 'apps/mobile/src/theme/palettes.ts');

function oklchToHex(input) {
  const m = /^oklch\(\s*([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)/i.exec(input.trim());
  if (!m) throw new Error(`unsupported color: ${input}`);
  const L = Number(m[1]);
  const C = Number(m[2]);
  const H = (Number(m[3]) * Math.PI) / 180;

  const a = C * Math.cos(H);
  const b = C * Math.sin(H);
  const labL = L + 0.3963377774 * a + 0.2158037573 * b;
  const labM = L - 0.1055613458 * a - 0.0638541728 * b;
  const labS = L - 0.0894841775 * a - 1.291485548 * b;

  const l3 = labL ** 3;
  const m3 = labM ** 3;
  const s3 = labS ** 3;

  let r = +4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3;
  let g = -1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3;
  let bl = -0.0041960863 * l3 - 0.7034186147 * m3 + 1.707614701 * s3;

  const gamma = (c) => {
    const v = c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055;
    return Math.round(Math.min(1, Math.max(0, v)) * 255);
  };
  const hex = (c) => gamma(c).toString(16).padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(bl)}`;
}

const MAP = {
  background: '--background',
  foreground: '--foreground',
  card: '--surface',
  'card-foreground': '--surface-foreground',
  popover: '--overlay',
  'popover-foreground': '--overlay-foreground',
  primary: '--default',
  'primary-foreground': '--default-foreground',
  secondary: '--surface-secondary',
  'secondary-foreground': '--surface-secondary-foreground',
  muted: '--surface-tertiary',
  'muted-foreground': '--muted',
  accent: '--accent',
  'accent-foreground': '--accent-foreground',
  destructive: '--danger',
  border: '--border',
  input: '--field-border',
  ring: '--focus'
};

function hexWithAlpha(hex, alpha) {
  const a = Math.round(alpha * 255)
    .toString(16)
    .padStart(2, '0');
  return `${hex}${a}`;
}

function buildTokens(vars) {
  const out = {};
  for (const [from, to] of Object.entries(MAP)) {
    if (vars[from] != null) out[to] = oklchToHex(vars[from]);
  }
  out['--separator'] = out['--border'];
  out['--segment'] = out['--surface-secondary'];
  out['--link'] = out['--focus'];
  out['--danger-foreground'] = out['--default-foreground'];
  out['--card-glass'] = hexWithAlpha(out['--surface'], 0.72);
  return out;
}

const files = readdirSync(paletteDir)
  .filter((f) => f.endsWith('.json') && f !== 'registry.json')
  .sort();

const palettes = files.map((file) => {
  const palette = JSON.parse(readFileSync(resolve(paletteDir, file), 'utf8'));
  const lightVars = palette.cssVars.light;
  const swatchVars = ['primary', 'accent', 'secondary', 'background'];
  return {
    id: palette.name,
    title: palette.title,
    category: CATEGORY[palette.name] || 'clean',
    swatches: swatchVars.map((k) => oklchToHex(lightVars[k])),
    light: buildTokens(palette.cssVars.light),
    dark: buildTokens(palette.cssVars.dark)
  };
}).filter((p) => p.category !== 'countries');

const fast = palettes.find((p) => p.id === 'fast');

mkdirSync(dirname(tokensPath), { recursive: true });
writeFileSync(
  tokensPath,
  `// generated by scripts/generate-theme.mjs from packages/web/ui/src/themes/palette/fast.json

export const fastLight = ${JSON.stringify(fast.light, null, 2)};

export const fastDark = ${JSON.stringify(fast.dark, null, 2)};
`
);

writeFileSync(
  palettesPath,
  `// generated by scripts/generate-theme.mjs — mirror of packages/web/ui/src/themes/palette/*.json

export type PaletteDef = {
  id: string;
  title: string;
  category: string;
  swatches: string[];
  light: Record<string, string>;
  dark: Record<string, string>;
};

export const PALETTES: PaletteDef[] = ${JSON.stringify(palettes, null, 2)};
`
);

console.log(`wrote ${tokensPath}`);
console.log(`wrote ${palettesPath} (${palettes.length} palettes)`);
